name: Build and Deploy Umami to Square Cloud

on:
  push:
    branches:
      - master # o main segun tu rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --include=dev --legacy-peer-deps

      - name: Build Umami
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_TYPE: postgresql
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: npm run build

      - name: Clean devDependencies
        run: npm prune --production --legacy-peer-deps

      - name: Deploy to Square Cloud
        uses: squarecloud/action@v2
        with:
          token: ${{ secrets.SQUARECLOUD_API_KEY }}
          app-id: ${{ secrets.SQUARECLOUD_APP_ID }}
